import { spawn } from 'node:child_process';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..'),target=process.argv[2]||pathToFileURL(join(root,'garden_ant_rivalry.html')).href;
const out=resolve(root,'artifacts','garden-ant-qa'),port=12000+Math.floor(Math.random()*20000),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const candidates=[process.env.BROWSER_BIN,'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe','/usr/bin/google-chrome','/usr/bin/chromium'].filter(Boolean);
let browserPath;
for(const candidate of candidates){try{await access(candidate,constants.X_OK);browserPath=candidate;break}catch{}}
if(!browserPath)throw new Error('Chrome/Edge not found. Set BROWSER_BIN to a Chromium executable.');
await mkdir(out,{recursive:true});
const profile=join(tmpdir(),`garden-ant-qa-${process.pid}-${port}`),browser=spawn(browserPath,['--headless=new','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-gpu-sandbox','--disable-gpu-shader-disk-cache','--disable-features=SkiaGraphite,DawnGraphite,WebGPU','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-address=127.0.0.1',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe'],windowsHide:true});
let browserStderr='';browser.stderr.on('data',chunk=>browserStderr+=chunk.toString());
let ws,seq=0;const pending=new Map(),consoleErrors=[],pageErrors=[],checks=[],artifacts=[];
const check=(name,ok,detail='')=>checks.push({name,ok:!!ok,detail});
try{
  let page;
  for(let i=0;i<50;i++){try{const pages=await(await fetch(`http://127.0.0.1:${port}/json`)).json();page=pages.find(p=>p.type==='page');if(page)break}catch{}await sleep(200)}
  if(!page)throw new Error(`Browser debugging endpoint unavailable (exit ${browser.exitCode}). ${browserStderr.slice(-1200)}`);
  ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});
  ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){pending.get(message.id).resolve(message);pending.delete(message.id)}if(message.method==='Runtime.exceptionThrown')pageErrors.push(message.params.exceptionDetails.text);if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')consoleErrors.push(message.params.args.map(a=>a.value||a.description||'').join(' '))});
  ws.addEventListener('close',event=>{const error=new Error(`CDP WebSocket closed (${event.code}: ${event.reason||'no reason'}). ${browserStderr.slice(-800)}`);for(const waiter of pending.values())waiter.reject(error);pending.clear()});
  const send=(method,params={})=>{const id=++seq,response=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP command timed out: ${method}`))},45000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}})});ws.send(JSON.stringify({id,method,params}));return response};
  const evaluate=async expression=>{const reply=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(reply.result.exceptionDetails)throw new Error(reply.result.exceptionDetails.text);return reply.result.result.value};
  const waitReady=async()=>{for(let i=0;i<60;i++){if(await evaluate(`!!window.__THREE_GAME_TEST_HOOKS__`))return;await sleep(200)}throw new Error('Game test hooks did not become ready')};
  const screenshot=async name=>{const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const file=join(out,name);const buffer=Buffer.from(shot.result.data,'base64');await writeFile(file,buffer);artifacts.push({file,bytes:buffer.length});check(`${name} is nonempty`,buffer.length>12000,`${buffer.length} bytes`)};
  const pixels=()=>evaluate(`window.__THREE_GAME_TEST_HOOKS__.sampleCanvas()`);

  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1280,height:720,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:target});await waitReady();
  const ready=await evaluate(`({label:begin.textContent,disabled:begin.disabled})`);check('login ready',ready.label==='Enter the garden'&&!ready.disabled,JSON.stringify(ready));
  await evaluate(`studentId.value='qa-desktop';begin.click()`);await sleep(400);let state=await evaluate(`window.__THREE_GAME_DIAGNOSTICS__.state`);check('game starts',state.running&&state.time<180,JSON.stringify(state));
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.placeAtSurfaceFood()`);check('surface food pickup',state.carrying&&state.surfaceCollected===1,JSON.stringify(state));
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.enterNest()`);check('carried food enters underground',state.mode==='underground'&&state.carrying,JSON.stringify(state));
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.placeAtChamber()`);check('underground delivery scores',state.blackFood===1&&state.undergroundDelivered===1&&!state.carrying,JSON.stringify(state));
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.placeNextToSolid();document.querySelector('#dig').click();window.__THREE_GAME_DIAGNOSTICS__.state`);check('dig opens one cell',state.dug===1&&await evaluate(`window.__THREE_GAME_TEST_HOOKS__.cell(14,3)`),JSON.stringify(state));
  await evaluate(`window.__THREE_GAME_TEST_HOOKS__.restart()`);check('restart restores excavated soil',!await evaluate(`window.__THREE_GAME_TEST_HOOKS__.cell(14,3)`),'cell 14,3 is solid again');
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.placeNearRed();document.querySelector('#attack').click();window.__THREE_GAME_DIAGNOSTICS__.state`);check('attack displaces rival',state.redDefeated===1,JSON.stringify(state));
  await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setState('active-play');window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(true)`);await sleep(150);await screenshot('desktop-surface.png');let pixel=await pixels();check('desktop canvas varied',pixel.variance>20&&pixel.colors>4,JSON.stringify(pixel));const desktopDiag=await evaluate(`window.__THREE_GAME_DIAGNOSTICS__`);check('desktop geometry budget',desktopDiag.renderer.geometries<200,JSON.stringify(desktopDiag.renderer));
  await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(false);window.__THREE_GAME_TEST_HOOKS__.setState('underground');window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(true)`);await sleep(150);await screenshot('desktop-underground.png');pixel=await pixels();check('underground canvas varied',pixel.variance>20&&pixel.colors>4,JSON.stringify(pixel));const underDiag=await evaluate(`window.__THREE_GAME_DIAGNOSTICS__`);check('underground draw-call budget',underDiag.renderer.calls<150,JSON.stringify(underDiag.renderer));check('soil is one instanced draw object',underDiag.entities.soilInstances===864&&underDiag.entities.soilDrawObjects===1,JSON.stringify(underDiag.entities));
  state=await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(false);window.__THREE_GAME_TEST_HOOKS__.setState('result')`);check('timed result state available',state.complete,JSON.stringify(state));const resultUi=await evaluate(`({hidden:results.hidden,download:download.getBoundingClientRect().height,summary:summary.textContent})`);check('result and PNG control visible',!resultUi.hidden&&resultUi.download>0&&resultUi.summary.includes('Automated QA'),JSON.stringify(resultUi));await screenshot('desktop-result.png');
  await evaluate(`again.click()`);check('play again returns to login',await evaluate(`!start.hidden&&results.hidden`));

  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});await send('Page.navigate',{url:target});await waitReady();await evaluate(`studentId.value='qa-mobile';begin.click();window.__THREE_GAME_TEST_HOOKS__.setState('active-play')`);await sleep(250);
  const layout=await evaluate(`(()=>{const up=document.querySelector('[data-move="up"]').getBoundingClientRect(),actions=document.querySelector('#actions').getBoundingClientRect(),stats=document.querySelector('#stats').getBoundingClientRect();return{up:{w:up.width,h:up.height},actions:{top:actions.top,bottom:actions.bottom},stats:{top:stats.top,bottom:stats.bottom},viewport:{w:innerWidth,h:innerHeight}}})()`);check('mobile touch target >=44px',layout.up.w>=44&&layout.up.h>=44,JSON.stringify(layout));check('mobile controls inside viewport',layout.actions.bottom<=layout.viewport.h&&layout.stats.top>=0,JSON.stringify(layout));
  const before=await evaluate(`window.__THREE_GAME_DIAGNOSTICS__.state.distance`),center=await evaluate(`(()=>{const r=document.querySelector('[data-move="up"]').getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:center.x,y:center.y,button:'left',clickCount:1});await sleep(500);await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:center.x,y:center.y,button:'left',clickCount:1});await sleep(120);const mobileInput=await evaluate(`({distance:window.__THREE_GAME_DIAGNOSTICS__.state.distance,active:document.querySelector('[data-move="up"]').classList.contains('active')})`);check('mobile input moves and releases',mobileInput.distance>before&&!mobileInput.active,JSON.stringify({before,...mobileInput}));await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(true)`);await screenshot('mobile-surface.png');pixel=await pixels();check('mobile canvas varied',pixel.variance>20&&pixel.colors>4,JSON.stringify(pixel));
  await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(false);window.__THREE_GAME_TEST_HOOKS__.setState('underground');window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(true)`);await sleep(150);await screenshot('mobile-underground.png');
  await evaluate(`window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(false);window.__THREE_GAME_TEST_HOOKS__.setState('result')`);const mobileResult=await evaluate(`(()=>{const b=download.getBoundingClientRect(),card=resultCard.getBoundingClientRect();return{button:{top:b.top,bottom:b.bottom},card:{top:card.top,bottom:card.bottom},viewport:innerHeight}})()`);check('mobile PNG button reachable',mobileResult.button.top>=0&&mobileResult.button.bottom<=mobileResult.viewport,JSON.stringify(mobileResult));await screenshot('mobile-result.png');
  check('no console errors',consoleErrors.length===0,consoleErrors.join('\n'));check('no page errors',pageErrors.length===0,pageErrors.join('\n'));
  const report={target,browserPath,passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,checks,consoleErrors,pageErrors,desktopDiagnostics:desktopDiag,undergroundDiagnostics:underDiag,artifacts};await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
}finally{try{ws?.close()}catch{}browser.stderr.destroy();browser.kill('SIGTERM');browser.unref()}
